// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pusqyigeqzvnqitqdics.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1c3F5aWdlcXp2bnFpdHFkaWNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NjYyODAsImV4cCI6MjA1OTE0MjI4MH0._Ql-Sx29pcwqgOZkGS0EGvTy1j8ihIy21X1y5h5WRJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);